### PR TITLE
More PostgreSQL datatypes support

### LINKED ISSUE #157: Support for UUID data type in postgres driver
Column type UUID in PostgreSQL is not currently recognized by geodiff.
- UUIDs in postgresql are 128-bit identifiers - https://www.postgresql.org/docs/9.1/datatype-uuid.html
- postgres functions to create standard uuids - https://www.postgresql.org/docs/9.1/uuid-ossp.html

On SQLite/GPKG side, there's no special UUID column type, so UUIDs would be treated as text, and if the column type name would be e.g. "uuid" then geodiff would try to convert those to postgresql's uuid column.

### LINKED ISSUE #176: Support for milliseconds in time data type

### LINKED ISSUE #177: Error when copying DB to GPKG for datatype character(50)
I have a database which has a field with: character(50). When I run DB-Sync, it produces the following error:
`GEODIFF: Error: unknown value type: character(50)`

### PR DESCRIPTION
**Pull request by alexbruy**
Adds support for more PostgreSQL datatypes:

- `character(N)` and `char(N)` (fixes #177)
- `numeric(M, N)`
- `uuid` (fixes #157)

Avoid datatypes conversion while making copy of the database if source and destitation drivers are the same. This allows to use native datatypes and avoid conversion issues (fixes #176).

### CODE REVIEW

**Comment by PeterPetrik** [comment]
best to review by @wonder-sk

File: geodiff/src/drivers/sqlitedriver.cpp [hunk 1]
```diff
@@ -222,7 +222,7 @@ std::vector<std::string> SqliteDriver::listTables( bool useModified )
 
     tableNames.push_back( tableName );
   }
-  if ( rc != SQLITE_DONE )
+  if ( rc != SQLITE_DONE && rc != SQLITE_ROW )
```
Comment (wonder-sk) [inline geodiff/src/drivers/sqlitedriver.cpp:225]: why do we need to handle SQLITE_ROW here as well? (and in other places in this file)

File: geodiff/src/drivers/postgresdriver.cpp [hunk 2]
```diff
@@ -471,15 +471,16 @@ static bool isColumnInt( const TableColumnInfo &col )
...
 }
 
 static bool isColumnText( const TableColumnInfo &col )
 {
   return col.type == "text" || startsWith( col.type.dbType, "text(" ) ||
          col.type == "varchar" || startsWith( col.type.dbType, "varchar(" ) ||
          col.type == "character varying" || startsWith( col.type.dbType, "character varying(" ) ||
-         col.type == "char" || col.type == "citext";
+         col.type == "char" || startsWith( col.type.dbType, "char(" ) || startsWith( col.type.dbType, "character(" ) ||
+         col.type == "citext" || col.type == "uuid";
```
Comment (wonder-sk) [inline geodiff/src/drivers/postgresdriver.cpp:483]: As uuid is not proper text field (and only we treat it as such for now), I think my preference would be not to have it listed in `isColumnText()` function, and rather in `resultToValue()` we would do something like:
```cpp
    else if ( isColumnText( col ) || col.type == "uuid" ) { ... }
```

File: geodiff/src/drivers/postgresdriver.cpp [hunk 3]
```diff
@@ -471,15 +471,16 @@ static bool isColumnInt( const TableColumnInfo &col )
 
 static bool isColumnDouble( const TableColumnInfo &col )
 {
-  return col.type == "real" || col.type == "double precision";
+  return col.type == "real" || col.type == "double precision" || startsWith( col.type.dbType, "numeric" );
```
Comment (wonder-sk) [inline geodiff/src/drivers/postgresdriver.cpp:474]: shall we also add "decimal" type ? postgres docs say it should be equivalent to "numeric" https://www.postgresql.org/docs/9.1/datatype-numeric.html

**Review by wonder-sk — COMMENTED** [review]
Great stuff. One thing I am wondering about is how we deal with "numeric" columns - we store them as doubles which provide 15 to 17 significant decimal digits, but what if someone stores a decimal number with 20 digits, and we would be loosing precision? I guess for now it would be OK if that would be a known limitation, I am just wondering if we can/should trigger some warnings in case we do a conversion where this would happen (i.e. not warn if someone uses `numeric(50)` with small numbers, only warn with `numeric(50)` and numbers with 16+ digits?

**Comment by alexbruy** [comment]
I was thinking about converting `decimal` and `numeric` to text to avoid loosing precision.

File: geodiff/src/drivers/sqlitedriver.cpp (hunk 1 above)
Comment (alexbruy) [reply geodiff/src/drivers/sqlitedriver.cpp:225]: Looks like the last time we call `sqlite3_step()` assigment does not work and we get following message in logs
```
SQLITE3 error [100]: another row available
```

Comment (alexbruy) [reply geodiff/src/drivers/sqlitedriver.cpp]: Should be fixed now. The proble was with geometry columns retrieval, we call `sqlite3_step()` only once, so it does not reach `SQLITE_DONE` state.

File: geodiff/src/tableschema.cpp [hunk 4]
```diff
@@ -110,7 +110,7 @@ TableColumnType postgresToBaseColumn(
   {
     type.baseType = TableColumnType::INTEGER;
   }
-  else if ( dbType == "double precision" || dbType == "real" )
+  else if ( dbType == "double precision" || dbType == "real" || startsWith( dbType, "numeric" ) )
```
Comment (wonder-sk) [inline geodiff/src/tableschema.cpp:113]: Shall we list `decimal` here as well if it is listed in postgresdriver.cpp?  (it's a bit annoying that this code is spread across two different places, maybe this whole function should be in the postgres driver, but that's probably for a separate refactoring PR)

Comment (alexbruy) [reply geodiff/src/tableschema.cpp]: Oh, you are right. My fault.

**Review by wonder-sk — APPROVED** [review]
Great, thanks!
